spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.80.128:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimail-product
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml  #扫描sql的文件
  global-config:
    db-config:
      id-type: auto  #自增主键
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10000
#  devtools:
#    restart:
#      exclude: static/**,public/**,config/application.yml
logging:
  level:
    com.atguigu.gulimall: debug



