spring:
  cloud:

#    sentinel:
#      transport:
#        #配置sentinel dashboard地址
#        dashboard: localhost:8080

    gateway:
      routes:
#        - id: test_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=uri,baidu
#
#        - id: qq_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=uri,qq
        - id: product_route
          #uri: lb://gulimail-product
          uri: http://localhost:10000
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: coupon_route
          uri: lb://gulimail-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: third_part_route
          #uri: lb://gulimail-third-part
          uri: http://localhost:30000
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*),/$\{segment}

        - id: member_route
          #uri: lb://gulimail-member
          uri: http://localhost:8000
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: ware_route
          #uri: lb://gulimail-ware
          uri: http://localhost:11000
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: order_route
          uri: lb://localhost:9000
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: admin_route
          #uri: lb://renren-fast
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}

        - id: gulimail_host_route
          #uri: lb://gulimail-product
          uri: http://localhost:10000
          predicates:
            - Host=gulimail.com,item.gulimail.com

        - id: gulimail_search_route
          #uri: lb://gulimail-search
          uri: http://localhost:12000
          predicates:
            - Host=search.gulimail.com

        - id: gulimail_auth_route
          #uri: lb://gulimail-auth-server
          uri: http://localhost:20000
          predicates:
            - Host=auth.gulimail.com

        - id: gulimail_cart_route
          uri: lb://localhost:30000
          predicates:
            - Host=cart.gulimail.com

        - id: gulimail_order_route
          uri: lb://gulimail-order
          predicates:
            - Host=order.gulimail.com

        - id: gulimail_member_route
          uri: lb://gulimail-member
          predicates:
            - Host=member.gulimail.com

        - id: gulimail_seckill_route
          uri: lb://gulimail-seckill
          predicates:
            - Host=seckill.gulimail.com

        - id: gulimail_coupon_routr
            uri: lb://gulimail-coupon
            predicates:
              - Path=/api/coupon/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}



#暴露所有端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

  ## 前端项目，/api
## http://localhost:88/api/captcha.jpg   http://localhost:8080/renren-fast/captcha.jpg
## http://localhost:88/api/product/category/list/tree http://localhost:10000/product/category/list/tree